os: Visual Studio 2015

platform:
  - x64

environment:
  nodejs_version: "7"

branches:
  only:
    - master

skip_tags: true

version: "{build}"

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install yarn -g nps
  - cd electron
  - yarn install
  - cd ..
  - cd client
  - yarn install

build_script:
  - nps build.prod
  - cd ..
  - cd electron
  - nps build.prod
  - nps release

before_build:
- ps: .\appveyor.before-build.ps1